# Encoding: UTF-8
# Written by: Signo-Net, Modified by Daniel Gagnon ( moi@danielgagnon.info )
# Email: clientes@signo-net.com
# Web: http://www.signo-net.com

# This work is licensed under a Creative Commons Attribution 3.0 License.
# [ http://creativecommons.org/licenses/by/3.0/ ]

# This means you may use it for any purpose, and make any changes you like.
# All we ask is that you include a link back to our page in your credits.

class CreateBruceSchneierFacts < ActiveRecord::Migration
  def self.up
    create_table :bruce_schneier_facts do |t|
      t.column :description, :text
    end

    BruceSchneierFact.create:description => "Guns don't kill people, Chuck Norris does."
BruceSchneierFact.create:description => "Albert Einstein wears Bruce Schneier pajamas"
BruceSchneierFact.create:description => "Anybody can invent a cryptosystem he cannot break himself.  Except Bruce Schneier."
BruceSchneierFact.create:description => "Bruce bench presses Core memory.  Encrypted Core memory."
BruceSchneierFact.create:description => "Bruce is so influential that a blog link is indistinguishable from a DDoS attack"
BruceSchneierFact.create:description => "Bruce Schneier accurately predicts the random."
BruceSchneierFact.create:description => "Bruce Schneier already knows what you got him for Christmas. "
BruceSchneierFact.create:description => "Bruce Schneier always has prime ribs and scrambled eggs for breakfast."
BruceSchneierFact.create:description => "Bruce Schneier always knows how many jelly beans are in the jar"
BruceSchneierFact.create:description => "Bruce Schneier and Lance Armstrong once had a contest to see who had more testicles.  Bruce was forced to forfeit when no one could decrypt his scrotum."
BruceSchneierFact.create:description => "Bruce Schneier beard has the bigger prime number of hairs"
BruceSchneierFact.create:description => "Bruce Schneier built his entire house out of Euler Bricks with integer space diagonals."
BruceSchneierFact.create:description => "Bruce Schneier can bend titanium alloy into a Penrose triangle."
BruceSchneierFact.create:description => "Bruce Schneier can break elliptic curve cryptography by bending it to a circle."
BruceSchneierFact.create:description => "Bruce Schneier can calculate the permanent of a matrix in polytime."
BruceSchneierFact.create:description => "Bruce Schneier can compute discrete logarithms in polynomial time. With his fists."
BruceSchneierFact.create:description => "Bruce Schneier can decipher NaN"
BruceSchneierFact.create:description => "Bruce Schneier can decrypt your PKI message with the public key."
BruceSchneierFact.create:description => "Bruce Schneier can detect entropy in a single bit"
BruceSchneierFact.create:description => "Bruce Schneier can detect stealth fighters with his antique radio."
BruceSchneierFact.create:description => "Bruce Schneier can determine if a program terminates just by looking at it. And then the program terminates itself."
BruceSchneierFact.create:description => "Bruce Schneier can divide by zero."
BruceSchneierFact.create:description => "Bruce Schneier can find Waldo in one chronon."
BruceSchneierFact.create:description => "Bruce Schneier can force Brownian motion to go in one direction only"
BruceSchneierFact.create:description => "Bruce Schneier CAN forge his own signature."
BruceSchneierFact.create:description => "Bruce Schneier can get exact answers using Monte Carlo methods with only one random sample."
BruceSchneierFact.create:description => "Bruce Schneier can guarantee fair exchange without trusted third parties."
BruceSchneierFact.create:description => "Bruce Schneier can hear sounds through vacuum."
BruceSchneierFact.create:description => "Bruce Schneier can log into any computer just by staring down the prompt."
BruceSchneierFact.create:description => "Bruce Schneier can make onion routers cry."
BruceSchneierFact.create:description => "Bruce Schneier can make pasta with ragu using the Sieve of Eratosthenes."
BruceSchneierFact.create:description => "Bruce Schneier can read and understand Perl programs."
BruceSchneierFact.create:description => "Bruce Schneier can read captchas."
BruceSchneierFact.create:description => "Bruce Schneier can receive and transmit RFID with his mind."
BruceSchneierFact.create:description => "Bruce Schneier can recite pi.  Backwards."
BruceSchneierFact.create:description => "Bruce Schneier can reuse his printer cartridges."
BruceSchneierFact.create:description => "Bruce Schneier can slam a logic gate. "
BruceSchneierFact.create:description => "Bruce Schneier can stop bullets with elliptic curves and can break elliptic curves with bullets."
BruceSchneierFact.create:description => "Bruce Schneier can tap fiber optic cable just by smelling it."
BruceSchneierFact.create:description => "Bruce Schneier can tell exactly where you are by reading ECHELON data. In realtime."
BruceSchneierFact.create:description => "Bruce Schneier can tell you where to find your GPG key into the digits of PI. "
BruceSchneierFact.create:description => "Bruce Schneier can tune an antenna by whistling the desired resonant frequency."
BruceSchneierFact.create:description => "Bruce Schneier can van eck phreak Waldo on every page from three bookshelves away. "
BruceSchneierFact.create:description => "Bruce Schneier can watch diplomatic channels using a TiVo."
BruceSchneierFact.create:description => "Bruce Schneier can write a recursive program that proves the Riemann Hypothesis. In Malbolge."
BruceSchneierFact.create:description => "Bruce Schneier can zoom in further than you can on Google Maps."
BruceSchneierFact.create:description => "Bruce Schneier counted an infinite set. Backwards."
BruceSchneierFact.create:description => "Bruce Schneier counts in binary. With his fists."
BruceSchneierFact.create:description => "Bruce Schneier cuts meat in prime number lengths."
BruceSchneierFact.create:description => "Bruce Schneier decided the color of the blue box"
BruceSchneierFact.create:description => "Bruce Schneier decrypts with a universal turing machine."
BruceSchneierFact.create:description => "Bruce Schneier derives his skills from arsenic contaminated squid jerky."
BruceSchneierFact.create:description => "Bruce Schneier does not get kidney stones. He gets Rosetta Stones."
BruceSchneierFact.create:description => "Bruce Schneier does not share forks when eating with dining philosophers."
BruceSchneierFact.create:description => "Bruce Schneier does not sleep. He preempts everything."
BruceSchneierFact.create:description => "Bruce Schneier drinks from a Klein Bottle"
BruceSchneierFact.create:description => "Bruce Schneier expects the Spanish Inquisition."
BruceSchneierFact.create:description => "Bruce Schneier factors integers in constant time."
BruceSchneierFact.create:description => "Bruce Schneier found a loophole in the LaMacchia Loophole."
BruceSchneierFact.create:description => "Bruce Schneier found the inverse of the constant zero function."
BruceSchneierFact.create:description => "Bruce Schneier generated his RSA key with the two largest prime numbers."
BruceSchneierFact.create:description => "Bruce Schneier gets the jokes in the Voynich MS."
BruceSchneierFact.create:description => "Bruce Schneier has a life. Not like you all NERDS."
BruceSchneierFact.create:description => "Bruce Schneier has already solved the Goldbach Conjecture.  He just enjoys watching us try."
BruceSchneierFact.create:description => "Bruce Schneier has an answer for the Cosmic AC"
BruceSchneierFact.create:description => "Bruce Schneier has a secret love child with Carol AND Alice."
BruceSchneierFact.create:description => "Bruce Schneier has a set of SSH Bump Keys."
BruceSchneierFact.create:description => "Bruce Schneier has the body of a model.  A threat model. "
BruceSchneierFact.create:description => "Bruce Schneier implanted the passphrase to your private key into your brain before you typed it"
BruceSchneierFact.create:description => "Bruce Schneier instantly knows the amount of Jelly Beans in a jar."
BruceSchneierFact.create:description => "Bruce Schneier invented his own numeral system with base infinity so he can count to infinity with only one digit."
BruceSchneierFact.create:description => "Bruce Schneier is able to read every Unlambda program."
BruceSchneierFact.create:description => "Bruce Schneier is always the man in the middle."
BruceSchneierFact.create:description => "Bruce Schneier is an asshole."
BruceSchneierFact.create:description => "Bruce Schneier is a proof that one way functions do not exist."
BruceSchneierFact.create:description => "Bruce Schneier is chock full of midichlorians."
BruceSchneierFact.create:description => "Bruce Schneier is hidden in your markov model"
BruceSchneierFact.create:description => "Bruce Schneier is the Bombe"
BruceSchneierFact.create:description => "Bruce Schneier is the guy that put Stephen Hawking in that wheelchair."
BruceSchneierFact.create:description => "Bruce Schneier is the root of all certificates."
BruceSchneierFact.create:description => "Bruce Schneier is the seed for your random number generator."
BruceSchneierFact.create:description => "Bruce Schneier keeps constant time."
BruceSchneierFact.create:description => "Bruce Schneier knew you would read this."
BruceSchneierFact.create:description => "Bruce Schneier knows where Carmen Sandiego is."
BruceSchneierFact.create:description => "Bruce Schneier knows where Grigori Perelman is."
BruceSchneierFact.create:description => "Bruce Schneier knows who the Anonymous Coward is"
BruceSchneierFact.create:description => "Bruce Schneier knows you are reading this."
BruceSchneierFact.create:description => "Bruce Schneier knows your password before you do."
BruceSchneierFact.create:description => "Bruce Schneier makes a mean Bearnaise sauce. But you need a password to access it. "
BruceSchneierFact.create:description => "Bruce Schneier never gets picked for a random search at the airport."
BruceSchneierFact.create:description => "Bruce Schneier once beat an asymmetric cipher into symmetry."
BruceSchneierFact.create:description => "Bruce Schneier once compressed a single bit of information to half its size."
BruceSchneierFact.create:description => "Bruce Schneier once could not decrypt something. Then he woke up."
BruceSchneierFact.create:description => "Bruce Schneier once decrypted a box of AlphaBits."
BruceSchneierFact.create:description => "Bruce Schneier once gave a roundhouse kick to the Internet. The backbone collapsed."
BruceSchneierFact.create:description => "Bruce Schneier once had a sperm count but the results were random each time they checked it."
BruceSchneierFact.create:description => "Bruce Schneier once killed a man using only linear cryptanalysis."
BruceSchneierFact.create:description => "Bruce Schneier once seeded a random number generator with the last output."
BruceSchneierFact.create:description => "Bruce Schneier PGP signs his grocery lists so that he can detect if someone has tampered with his milk."
BruceSchneierFact.create:description => "Bruce Schneier puts his pants on in constant time... no matter how many legs he has."
BruceSchneierFact.create:description => "Bruce Schneier puts the AES in asskicking."
BruceSchneierFact.create:description => "Bruce Schneier reads RFID cards with the knuckles of his clenched fist."
BruceSchneierFact.create:description => "Bruce Schneier reads Slashdot with an oscilloscope."
BruceSchneierFact.create:description => "Bruce Schneier rounds to infinity."
BruceSchneierFact.create:description => "Bruce Schneiers Erdös Number is smaller than zero."
BruceSchneierFact.create:description => "Bruce Schneier sits at the top of the arithmetical hierarchy."
BruceSchneierFact.create:description => "Bruce Schneier slashdotted slashdot."
BruceSchneierFact.create:description => "Bruce Schneier solved the two envelope paradox by taking both."
BruceSchneierFact.create:description => "Bruce Schneier speaks fluent Navajo."
BruceSchneierFact.create:description => "Bruce Schneier stole my bike."
BruceSchneierFact.create:description => "Bruce Schneier tampers with tamperproof hardware."
BruceSchneierFact.create:description => "Bruce Schneier tapdances in Morse Code."
BruceSchneierFact.create:description => "Bruce Schneier taught Chuck Norris how to divide by zero as they stood silent in an elevator."
BruceSchneierFact.create:description => "Bruce Schneier taught his dog to do a secure handshake"
BruceSchneierFact.create:description => "Bruce Schneier ties his shoes with a Gordian Knot"
BruceSchneierFact.create:description => "Bruce Schneier turns snake oil into biodiesel in his garage."
BruceSchneierFact.create:description => "Bruce Schneier uses a different salt for his soup everyday."
BruceSchneierFact.create:description => "Bruce Schneier uses a trinary CPU in his workstation."
BruceSchneierFact.create:description => "Bruce Schneier was born with the Phaistos Disk in his fist."
BruceSchneierFact.create:description => "Bruce Schneier whistles white noise."
BruceSchneierFact.create:description => "Bruce Schneier won the coin toss between Bill Hewlett and Dave Packard."
BruceSchneierFact.create:description => "Bruce Schneier writes his personal journal in Linear A."
BruceSchneierFact.create:description => "Bruce Schneier wrote Blowfish in Malbolge. "
BruceSchneierFact.create:description => "Bruce Schneier wrote the random number generator used to generate thermal noise"
BruceSchneierFact.create:description => "Bruce uses Turing tape as toilet paper."
BruceSchneierFact.create:description => "Consider an arbitrary stochastic variable. Bruce Schneier will have an effect on its outcome. "
BruceSchneierFact.create:description => "If Bruce Schneier made laws nobody could break them."
BruceSchneierFact.create:description => "It is impossible to hide information from Bruce Schneier. Not even by destroying it."
BruceSchneierFact.create:description => "I wear Bruce Schneier brand underpants to protect me from binarysexuals"
BruceSchneierFact.create:description => "lolcats are Bruce Schneiers proof that steganography works."
BruceSchneierFact.create:description => "Most people salt their hash. Bruce salt and peppers his."
BruceSchneierFact.create:description => "My firewall cannot block www.schneier.com."
BruceSchneierFact.create:description => "No subgroup is hidden from Bruce Schneier."
BruceSchneierFact.create:description => "No TOR destinations are hidden from Bruce Schneier."
BruceSchneierFact.create:description => "Once Bruce Schneier was kidnapped and taken out of the country. His kidnappers got picked up and charged with a violation of US cryptography export laws."
BruceSchneierFact.create:description => "Only Bruce Schneier will be able to decipher the steganographic payload hiding in this fact."
BruceSchneierFact.create:description => "Only one security god has a surname with three adjacent vowels."
BruceSchneierFact.create:description => "Others test numbers to see whether they are prime.  Bruce decides whether a number is prime."
BruceSchneierFact.create:description => "Parallel lines meet at Bruce Schneier."
BruceSchneierFact.create:description => "Perfect Forward Secrecy is when Bruce Schneier whispers something in your ear."
BruceSchneierFact.create:description => "Schneier knows if Reiser did it."
BruceSchneierFact.create:description => "Science is defined as mankinds futile attempt at learning Bruce Schneiers private key"
BruceSchneierFact.create:description => "Stephen Hawking changed his opinion on the information paradox when he realized that not even black holes can hide information from Bruce Schneier."
BruceSchneierFact.create:description => "Strong cryptography does not exist for Bruce Schneier. There is only weak and less weak cryptography."
BruceSchneierFact.create:description => "The Dining Cryptographers always wait until Bruce Schneier has been served."
BruceSchneierFact.create:description => "The enemy only knows the system because Bruce Schneier wants him to know the system."
BruceSchneierFact.create:description => "The last cryptologist who questioned Bruce Schneier was found floating face down in his own entropy pool."
BruceSchneierFact.create:description => "The only fully secure symmetric cryptosystem is Bruce Schneier looking in a mirror."
BruceSchneierFact.create:description => "The phonograph record included on the Voyager probe contains a hidden watermark inserted by Bruce Schneier."
BruceSchneierFact.create:description => "There are no composite numbers. Only prime numbers Bruce has broken into smaller pieces."
BruceSchneierFact.create:description => "There are no finite state machines. There are only a series of states that Bruce Schneier allows to exist."
BruceSchneierFact.create:description => "There are no prime numbers. Only numbers that Bruce Schneier does not want you to factor."
BruceSchneierFact.create:description => "There is no Information Theory. Just data that Bruce Schneier allows to be quantified and transmitted on a channel."
BruceSchneierFact.create:description => "There is no protocol to play Mental Poker that prevents Bruce Schneier keeping aces up his sleeve."
BruceSchneierFact.create:description => "The spacing between Bruce Schneiers ribs forms an Optimal Golomb Ruler."
BruceSchneierFact.create:description => "The universe exists because Bruce needed a reference platform"
BruceSchneierFact.create:description => "This fact has been removed... by Bruce Schneier"
BruceSchneierFact.create:description => "When Bruce Schneier calculates the square root of a negative number the result is real."
BruceSchneierFact.create:description => "When Bruce Schneier reads from his entropy pool the universe contracts"
BruceSchneierFact.create:description => "When Bruce Schneier signs a legal document it can no longer be compressed."
BruceSchneierFact.create:description => "When Bruce Schneier skateboards he uses one time knee pads"
BruceSchneierFact.create:description => "Your sysadmin can reset your password. Bruce Schneier can reset your fingerprints."

  end

  def self.down
    drop_table :chuck_norris_facts
  end
end

